services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: procurement_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: registry.gitlab.com/komyor/ai-procurement-system:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8000:8000"

volumes:
  mysql_data:
